### ISSUE TITLE
The MD tutorial files in tests/test_md are not updated

### ISSUE THREAD

**Issue by MrigankaParasar** [Quantum-Dynamics-Hub/libra-code#117]
The details are attached in a pdf file : [Libra Molecular Dynamics Error.pdf](https://github.com/Quantum-Dynamics-Hub/libra-code/files/6568480/Libra.Molecular.Dynamics.Error.pdf)

**Comment by alexvakimov** [comment]
Hi Mriganka, 

Thank you for reporting this problem. It originates from couple reasons: a) Python 2 to Python 3 transition was made, but this tutorial/example (potentially with others) was not yet updated; b) some of the functions changed their signatures since the time the examples were first published. 

I have just implemented these corrections and it runs on my system. Please update your code to the latest version on the `devel` branch (just `git pull origin devel`, while being on the `devel` branch locally). You don't need to recompile Libra itself - my commit just changes the example files. 

Please let me know how it goes. Also, please don't hesitate to open issues if you run into other problems.

Best,
Alexey

**Comment by MrigankaParasar** [comment]
Thank you. The code ran successfully.
