### ISSUE TITLE
make libint2 errors 

### ISSUE THREAD

**Issue by DanteArchangel** [Quantum-Dynamics-Hub/libra-code#123]
Getting compile error, even after trying to use solutions from previous issue.
`
make[2]: *** [src/libint2_wrappers/CMakeFiles/libint2_wrappers.dir/build.make:95: src/libint2_wrappers/CMakeFiles/libint2_wrappers.dir/liblibint2_wrappers.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2612: src/libint2_wrappers/CMakeFiles/libint2_wrappers.dir/all] Error 2
[ 51%] Linking CXX shared library libmolint.so
[ 51%] Built target molint
[ 51%] Linking CXX shared library libqobjects.so
[ 51%] Built target qobjects
make: *** [Makefile:103: all] Error 2
` 
I have libint2   2.6.0   and as recommended here (https://github.com/Quantum-Dynamics-Hub/libra-code/issues/121) changed CMakeLists.txt, nothing helped.

**Comment by alexvakimov** [comment]
Our recent practice showed that if one can follow the step-by-step instructions on the README.md in the **devel**  branch, everything (cmake, build, and import) works quite well. Just a few days ago, we installed it on a new computing system. Having software pieces installed in different parts of your system doesn't help since there may always be conflicts. That's why I recommend installing it via conda - this is what, you can be sure about the composition of your environment. We can set up a meeting to try to go over the installation, if you like (please join the Quantum-Dynamics-Hub Slack and DM me).

**Comment by DanteArchangel** [comment]
I have tried once again on another system, starting from installing conda and everything worked, so i guess i had some issues with my conda itself. Thank you!
